### ISSUE TITLE
Function type with single return value enclosed by parens handled incorrectly

### ISSUE THREAD

**Issue by stravant** [JohnnyMorganz/StyLua#749] opened 2023-09-01 00:21 UTC
# Observed Behavior

Works:
```
function foo(): (number) -> number
end
```

Yields an `error: could not format file`:
```
function foo(): (number) -> (number)
end
```

# Expected Behavior

This should not throw an error since enclosing a single return value in parenthesis is valid Luau syntax.

**Comment by JohnnyMorganz** [comment] 2023-09-02 00:11
What version of stylua are you using? I cannot reproduce this on the latest version

**Comment by JohnnyMorganz** [comment] 2023-09-16 19:11
Closing since I cannot reproduce. If you have any further info, feel free to reopen

**Closed by JohnnyMorganz** 2023-09-16 19:11 UTC
Labels: bug
