### ISSUE TITLE
Question- Support ? and ` characters? 

### ISSUE THREAD

**Issue by Gellipapa** [JohnnyMorganz/StyLua#731] opened 2023-07-09 14:56 UTC
Hi! I have a question: is there any way to make the formatter run longer if it finds these two characters somewhere?

The problem is I would use this formatting in code within the FiveM framework and they have solved it to use the optional ? and the backtick ` in lua and when I try to run the formatting I get an error that there is a syntax error, which is perfectly legitimate. 

I'll try to include it, but maybe you have a better idea how to do it. Probably if it could be solved many people would use it in the FiveM environment with a pretty large developer community.

What I'm thinking is that there might be some skip option that if you find one of these you can ignore.

Thanks for your reply in advance and great this formatting script is still :) 

Error message: 
![image](https://github.com/JohnnyMorganz/StyLua/assets/22717950/afb4ba76-526b-43cc-b7bb-d73678f96df4)

**Comment by matthargett** [comment] 2023-07-09 15:28
This would need to be a feature added to the full-moon library. Can you file an issue in their repo and include a small code snippet that reproduces the issue?

**Comment by Gellipapa** [comment] 2023-07-09 17:30
> This would need to be a feature added to the full-moon library. Can you file an issue in their repo and include a small code snippet that reproduces the issue?

Hi! I don't quite understand what this full-moon library means. Could you explain it better? 

On this link you can access the file you tried to format and find the error on line 162.
https://github.com/esx-framework/esx_core/blob/main/%5Bcore%5D/esx_multicharacter/server/main.lua

Workflow step:
```
      - name: Install stylua and format files
        uses: JohnnyMorganz/stylua-action@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: v0.18.0
          args: -- .
```

Thanks for the reply in advance.

**Comment by JohnnyMorganz** [comment] 2023-07-11 11:54
The library we use to parse Lua code is called full-moon: https://github.com/Kampfkarren/full-moon
Support will need to be added there for FiveM-style Lua code. Once that's done, stylua will be able to format this code.

It's probably best to open and track an issue there. I see the example of using `?` in the link you gave above. Can you also include an example of backticks use?

It is difficult for us to "skip" these characters, as the formatter relies on a character parse tree

**Comment by Gellipapa** [comment] 2023-07-11 14:15
@JohnnyMorganz 
Hi! Thanks for the reply, I understand, I'll open a problem and try to add this specific skip logic.

I have checked the backtick and it does throw an error as I looked at it to skip, so as you can see in the commit below, when it was running there was no error and it did not replace them with other characters, so sorry for my misleading, but it works. 

https://github.com/Gellipapa/test_version/commit/5dfdd24e492988bfc7a6e9b7371a802720e74b96?diff=split

These two specific cases are in FiveM so I thought that might be a problem too. So just the ?. the problem is the backtick is handled by the script.

**Comment by Gellipapa** [comment] 2023-07-12 00:47
@JohnnyMorganz Hi!  I looked at the code can you give me some guidance on where to put this in the full moon? I have not dealt with the rust language before. 

I'm thinking here in which file should I look because I saw in pull_request a tokenizer folder but main doesn't look like this or maybe there is no description how I can test this full-moon directory locally? 

Thanks in advance for the answer.

**Comment by JohnnyMorganz** [comment] 2023-12-30 16:18
Hey sorry, it looks like I must have missed your message.

As mentioned on the issue you opened in full-moon, you would have to wait for the full-moon rewrite to complete which makes way for adding different styles of parsers. I am happy to help once that rewrite is done.

I am going to close this issue for now, as there is not much we can do here. When support is added in full-moon, I am happy to revisit this here in StyLua.

**Closed by JohnnyMorganz** 2023-12-30 16:18 UTC

**Comment by Gellipapa** [comment] 2024-01-22 19:07
@JohnnyMorganz Hi! I recently asked the creator of full-moon about when the parse rewrite will be done and he said that it will be done before the end of the day. I checked the next day and it was already merged. 

I would like some help on how I can ?. and ` manage it using stylua and full-moon. 

Thank you very much for your reply in advance.
