### ISSUE TITLE
It requires 2 runs of Stylua so stabilize the output for some examples

### ISSUE THREAD

**Issue by ktrz** [JohnnyMorganz/StyLua#430] opened 2022-04-01 06:20 UTC
All of the examples are run wth the following configuration:

StyLua version: `13.0.0`

`.stylua.toml` file:
```toml
column_width = 100
line_endings = "unix"
indent_type = "T=tabs"
indent_width = 4
quote_style = "double"
```

### The following examples require 2 runs of StyLua to produce proper (and stable) results

```lua
type Foo<T = --[[leading]]
string
--[[trailing]]> = { baz: T, }
```

```lua
type Bar<T
--[[ Trailing comment ]]> = {}
```

```lua
-- This is a comment before
type Foo = --[[ Comment before Bar ]]
Bar<--[[ Before X ]]
X, --[[ After X ]]
--[[ Before Y ]]
Y, --[[ After Y ]]
--[[ Before Z ]]
Z
--[[ After Z ]]> -- This is a comment after
```

```lua
type OffsetEnum = { [string]: number, }
local OffsetEnum = {aValue = 10, anotherValue = 11, yetAnotherValue = 12, reset = 0, postReset = 1}
```

### Results after the first run

```lua
type Foo<
	T =  --[[leading]]string	--[[trailing]]

> = { baz: T }

----------------

type Bar<T--[[ Trailing comment ]]
> = {}

-----------------

-- This is a comment before
type Foo =  --[[ Comment before Bar ]]Bar<--[[ Before X ]]X,  --[[ After X ]]--[[ Before Y ]]
Y,  --[[ After Y ]]--[[ Before Z ]]
Z--[[ After Z ]]
> -- This is a comment after

-------------------

type OffsetEnum = { [string]: number }
local OffsetEnum =
	{
		aValue = 10,
		anotherValue = 11,
		yetAnotherValue = 12,
		reset = 0,
		postReset = 1,
	}
```

### Results after the second and any consecutive run

```lua
type Foo<
	T =  --[[leading]]string --[[trailing]]
> = { baz: T }

----------------

type Bar<
	T--[[ Trailing comment ]]
> = {}

-----------------

-- This is a comment before
type Foo =  --[[ Comment before Bar ]]Bar<--[[ Before X ]]X,  --[[ After X ]]--[[ Before Y ]]Y,  --[[ After Y ]]--[[ Before Z ]]Z--[[ After Z ]]> -- This is a comment after

-------------------

type OffsetEnum = { [string]: number }
local OffsetEnum = {
	aValue = 10,
	anotherValue = 11,
	yetAnotherValue = 12,
	reset = 0,
	postReset = 1,
}
```

**Comment by JohnnyMorganz** [comment] 2022-04-01 17:00
This looks like a duplicate of #397, but with some more good test cases to use. I'll move it over there

**Closed** 2022-04-01 17:01 UTC
Labels: bug, duplicate
