### ISSUE TITLE
[Luau] if-then-else expressions should breaking into multiple lines at a shorter length.

### ISSUE THREAD

**Issue by MaximumADHD** [JohnnyMorganz/StyLua#554] opened 2022-08-23 21:31 UTC
In Roblox's [Lua Style Guide](https://roblox.github.io/lua-style-guide/#if-then-else-expressions), it is noted that it's ok to break expressions up into multiple lines like so:

```lua
local player = assert(Players.LocalPlayer)
local character = player.Character
	
local humanoid = if character
    then character:FindFirstChildOfClass("Humanoid")
    else nil
	
if humanoid then
    -- neat
end
```

StyLua currently forces `if-then-else` blocks to be in one line if their length is below a certain threshold that is... a bit longer than necessary:

```lua
-- Line break doesn't kick in.
local dummy = if character then character:FindFirstChild("abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXY") else nil

-- Line break *does* kick in.
local dummy = if character
    then character:FindFirstChild("abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ")
    else nil
```

I'm not sure if this is a limitation or something that can be configured, but I think the way I styled it in that first code sample is perfectly reasonable and shouldn't be auto-formatted away.

Right now it is forced to look like this:
```lua
local player = assert(Players.LocalPlayer)
local character = player.Character

local humanoid = if character then character:FindFirstChildOfClass("Humanoid") else nil

if humanoid then
    -- neat
end
```

**Comment by LastTalon** [comment] 2022-08-25 16:33
This looks like its currently very close to the default column width of 120 characters. Roblox has since updated their style guide to recommend 100 columns (it used to recommend 120). If you configure stylua with `column_width = 100` does it seem to wrap more reasonably to you?

**Comment by JohnnyMorganz** [comment] 2022-08-27 09:19
This is a duplicate of #465.
As mentioned there, the formatting here is technically correct - it falls under the provided column width of 120.
In these cases now though, it seems 120 is too large. As stated in the previous comment, the style guide was updated to use 100 columns, which might produce a better formatting here.

There are only 2 potential options we could do here, but I don't like either of them:
- Rely on the input formatting. This is very much something I do not want to do
- Enforce an arbitrary "lower" column width for if expressions in particular. This makes more sense when the column width is set to 120, but if its set to 80 then this lower width becomes restrictive.

**Closed by JohnnyMorganz** 2022-08-27 09:19 UTC
