### ISSUE TITLE
Optional parentheses

### ISSUE THREAD

**Issue by cloggier** [JohnnyMorganz/StyLua#133] opened 2021-04-30 17:58 UTC
Hey, great styler! Thanks a lot.

One thing I would like to change is to have an option so StyLua does not add parenthesis to code that does not require them.
Like function calls with single argument, etc. This answer describes it better: https://stackoverflow.com/a/36126475

I understand that this is very personal, I for one, would like to keep using that syntactic sugar as it makes code easier to read for me.

**Comment by cloggier** [comment] 2021-04-30 18:55
I did try to look for other issues, apologies for bringing it up again. Thanks for considering it this time! Fingers crossed. :)

**Comment by cloggier** [comment] 2021-05-01 07:19
I was also thinking that maybe there could be an umbrella option for all syntactic sugar that's available in lua, all enabled at once (if there is anything else, that is, which I am not even sure about). That would limit additional options added to your awesome project, but allow users to chose if they want their code sugar coated or not.

**Comment by disrupted** [comment] 2021-05-03 09:22
I agree with @cloggier, this would be a great addition. Since it's a very lua-specific thing I'd like to embrace it

**Comment by JohnnyMorganz** [comment] 2021-05-11 16:54
Seeing as there is a bit of demand for this, I decided to have a go at implementing this and see how it turns out. I published what I have currently to the `no-parens` branch. There is a new config option available, `no_call_parentheses`, which is a boolean defaulting to `false`. If enabled, parentheses will be omitted around **all** single argument function calls, where the argument is a string literal or a table. A single space is also placed in between the call identifier and the argument.

This isn't a style I would normally use, so I would appreciate if some people would be able to test it out and see how it looks (also, if it leads to any syntax errors or changes in semantics). It can be installed directly from cargo using `cargo install --git https://github.com/JohnnyMorganz/StyLua.git --branch no-parens`. [Note, this is based of current master, so it has some other unpublished changes, which are available to view in the changelog]. If anybody has any changes they would like to recommend after testing it out, please do let me know.

Please also note that I have not confirmed yet whether I will add this in. I am still not 100% sure, and I may not add it in the end.

(CC @tjdevries @lucastrvsn, as you commented on #65 for this request)

**Comment by lucastrvsn** [comment] 2021-05-11 20:35
this is awesome! Thank you so much @JohnnyMorganz !

**Comment by cloggier** [comment] 2021-05-14 08:56
Also tested it now, works great! Thanks a lot!

**Comment by JohnnyMorganz** [comment] 2021-05-19 21:13
Question for people interested in this style:
One thing that looks a bit off to me sometimes is the space in between the call name and its arguments. When calling by itself it looks alright, such as
```lua
local foo = require "string"
```
But, when the call is inside a chain, it seems a bit odd:
```lua
something "foo".setup({
    -- ...
})
```
As compared to removing the space:
```lua
something"foo".setup({
    -- ...
})
```
Would this be something thats preferred? i.e., if the call is preceded by another suffix like an index or another call, then remove the leading space. Its an extremely minor point, and the current setup is much easier right now (changing this would mean it would have to look forward at the next AST node which it currently doesn't have access to), but I just want to make sure I get the style "perfect" :)

Or alternatively, maybe just no space at all?

Also if there's anything else you would like to point out, do let me know!

**Comment by cloggier** [comment] 2021-05-19 21:41
What I actually prefer is something like:
```lua
require "foo".setup {}
```

1. with spaces
2. without parens around single argument in `setup` call.


Does that help? 

Also super happy to see you go further into it, was bit afraid of seeing rejecting message when notification popped out. :)

**Comment by JohnnyMorganz** [comment] 2021-05-19 22:07
Whoops, my mistake - the parentheses shouldn't actually be there! What you wrote is actually what will happen, I accidently put those parens out of habit I guess 😄

**Comment by disrupted** [comment] 2021-05-20 16:28
@JohnnyMorganz same, looks great to me as it is! Thanks for implementing it.

**Comment by JohnnyMorganz** [comment] 2021-05-20 18:58
> `no_call_parentheses` option could take a list / set of values where it would tell you when to remove the parentheses by types.

Unfortunately, I think it is unlikely that the option will become any more diluted than a simple on/off here. I do, however, want to make sure that the style, when enabled, is good enough to be used in its complete form.

> I generally do not like the look of `require "my_mod".value` because it always looks like `.value` is accessing the string -- particularly to new users. so this could always be `require('my_mod').value`.

This is also something I am quite wary about, which is partly why I brought up the spaces issue. Quickly glancing over it does indeed make the index look like its part of the string, rather than the output of the function, and like you pointed out this may be confusing for users new to Lua syntax. The two options here could be to remove the leading space, as it makes it a bit better to understand, or to keep/add the parentheses (Note: these would only apply if the next AST node was either `.foo` or `:foo`). Personally, I would also lean towards using parentheses, as it makes it removes the ambiguity completely, but it may go against the "style" of "no_call_parentheses".
I need to think further on this, because I do not want the formatting to make code harder to parse by a human.

**Comment by tjdevries** [comment] 2021-05-20 19:28
> Personally, I would also lean towards using parentheses, as it removes the ambiguity completely, but it may go against the "style" of "no_call_parentheses".

This would be a great solution for me that balances low configuration and easy readability.

```lua

local foo = require "foo"
local has_parens = require("configuration").has_parens

local opt = my_function {
  hello = true
}

local still_got_em = my_function({
  config = true,
  value = "yup",
}):method()
```

This seems quite good IMO (not sure if I missed any cases to consider)

**Comment by JohnnyMorganz** [comment] 2021-05-21 17:46
Hey all, I updated the `no_parens` branch to accommodate for these changes: StyLua will now keep/add parentheses if the next node is either `.foo` or `:foo`, so as to help the readability of the code. The example that @tjdevries provided above is pretty much exactly what it will do now.

As previous, the branch is available to test out using `cargo install --git https://github.com/JohnnyMorganz/StyLua.git --branch no-parens`. I also merged the latest snapshot of the main branch into `no_parens`, so it may include some other changes - you can find them in the changelog.

I think this will be the final style going forward, so if you try it out, do let me know if there are any issues with it, thanks!

**Comment by lucastrvsn** [comment] 2021-05-21 18:52
@JohnnyMorganz Again, everything is perfect for me! Teej's example makes it more clear what it should do.

I'm using it for the past few days, and I'm loving the speed and robustness. Thank you!

**Comment by cloggier** [comment] 2021-05-21 19:10
Same here, all works super well. Thanks!

**Comment by tjdevries** [comment] 2021-05-24 12:56
I played with it a bit and don't have any other suggestions. I think it looks really good (and strikes a good balance between configuration and opinionated formatter)

**Comment by JohnnyMorganz** [comment] 2021-06-12 22:22
Hey all, #167 has been merged, and I'm hoping to get a new release out in the next day or two. Hope it works well for you all!

**Closed** 2021-06-12 22:21 UTC
Labels: enhancement

**Comment by tjdevries** [comment] 2021-06-13 00:45
Thanks for the great work :) looking forward to adding this to bascially all my lua projects :)

**Comment by JohnnyMorganz** [comment] 2021-06-15 17:24
v0.9.0 is now released and this should now be available to use: https://github.com/JohnnyMorganz/StyLua/releases/tag/v0.9.0

**Comment by tjdevries** [comment] 2021-06-15 20:36
Great :) Thanks!
