### ISSUE TITLE
Parentheses removed that changes math

### ISSUE THREAD

**Issue by Nezuo** [JohnnyMorganz/StyLua#80] opened 2021-03-17 03:37 UTC
```lua
local function levenshteinRatio(str1, str2)
	local matrix = {}
	local len1 = #str1 + 1
	local len2 = #str2 + 1

	for i = 1, len2 do
		matrix[i] = { i - 1 }
	end

	for j = 1, len1 do
		matrix[1][j] = j - 1
	end

	for i = 2, len2 do
		for j = 2, len1 do
			if string.byte(str2, i - 1) == string.byte(str1, j - 1) then
				matrix[i][j] = matrix[i - 1][j - 1]
			else
				matrix[i][j] = math.min(
					matrix[i - 1][j - 1] + 1, -- Substitution
					matrix[i][j - 1] + 1, -- Insertion
					matrix[i - 1][j] + 1 -- Deletion
				)
			end
		end
	end

	return (#str1 + #str2 - matrix[len2][len1]) / (#str1 + #str2)
end
```

The return statement turns into:
```lua
return #str1 + #str2 - matrix[len2][len1] / #str1 + #str2
```

**Comment by JohnnyMorganz** [comment] 2021-03-17 10:17
Duplicate of #66

This has already been fixed on master (see https://github.com/JohnnyMorganz/StyLua/issues/54#issuecomment-800206792), but it is currently not released. Master should be stable, so you could build locally if you want it now

**Closed** 2021-03-17 10:17 UTC
Labels: duplicate
