### ISSUE TITLE
Bug: Automatically add " : " to directory paths (Workflows, Stylua-action)

### ISSUE THREAD

**Issue by Alvin-He** [JohnnyMorganz/StyLua#247] opened 2021-08-27 04:58 UTC
The title said all. I got a simple GitHub Actions workflow running with the code shown down here: 
```
name: DevPull
on:
  # A manually triggered workflow, just for testing  
  workflow_dispatch: 
    #inputs:
     # branch:   #don't worry about this, this is for some other stuff 
      
jobs:
  # check syntax 
  check: 
    runs-on: ubuntu-latest 
    steps:
      - name: StyLua
        # uses: JohnnyMorganz/stylua-action@7aaf2110b04b420e39d5a9d8834d3104b7ccd1e1
        uses: JohnnyMorganz/stylua-action@1.0.0
        with:
          # The GITHUB_SECRET token
          token: ghp_***********************************
          # CLI Arguments to pass to StyLua
          args: 
            stylua https://github.com/Alvin-He/Project_RAI/tree/src
``` 
Looks like a code without problems. Alought what I got was not so promising: 
``` 
2021-08-27T04:30:35.4084077Z Prepare workflow directory
2021-08-27T04:30:35.4687307Z Prepare all required actions
2021-08-27T04:30:35.4697712Z Getting action download info
2021-08-27T04:30:35.6999411Z Download action repository 'JohnnyMorganz/stylua-action@1.0.0' (SHA:7aaf2110b04b420e39d5a9d8834d3104b7ccd1e1)
2021-08-27T04:30:37.6476853Z ##[group]Run JohnnyMorganz/stylua-action@1.0.0
2021-08-27T04:30:37.6477691Z with:
2021-08-27T04:30:37.6478795Z   token: ***
2021-08-27T04:30:37.6479668Z   args: stylua https://github.com/Alvin-He/Project_RAI/tree/main/src
2021-08-27T04:30:37.6480512Z   version: 0.10.1
2021-08-27T04:30:37.6480945Z ##[endgroup]
2021-08-27T04:30:38.5383114Z [command]/usr/bin/unzip -q /home/runner/work/_temp/eb1436bf-2711-4dfb-9151-ac805b559b0f
2021-08-27T04:30:38.6438189Z [command]/usr/bin/chmod +x /home/runner/work/_temp/9146f253-9139-4b0a-91ab-dac074472522/stylua
2021-08-27T04:30:38.6477026Z [command]/home/runner/work/_temp/9146f253-9139-4b0a-91ab-dac074472522/stylua stylua https://github.com/Alvin-He/Project_RAI/tree/main/src
2021-08-27T04:30:38.6502808Z error: could not walk: stylua: IO error for operation on stylua: No such file or directory (os error 2)
2021-08-27T04:30:38.6505686Z error: could not walk: https://github.com/Alvin-He/Project_RAI/tree/main/src: IO error for operation on https://github.com/Alvin-He/Project_RAI/tree/main/src: No such file or directory (os error 2)
2021-08-27T04:30:38.6517086Z ##[error]The process '/home/runner/work/_temp/9146f253-9139-4b0a-91ab-dac074472522/stylua' failed with exit code 2
2021-08-27T04:30:38.6597171Z Cleaning up orphan processes
``` 

the URL: https://github.com/Alvin-He/Project_RAI/tree/main/src should be valid if there aren't the ":" at the end of /src: . Even if the program can't use the URL to get to the file, when I copied it to the browser, it should still take me to that branch. However, it gave me a 404 error. I tried using "src/" "/src" "https://github.com/Alvin-He/Project_RAI main src/" in the arguments sections. Non of them returned me an valid address in the log.  I'm new to making work flows, but I don't think there's a problem in my code. (the repo is a private one, so I don't think any body have access to it. But I'm sure that link is valid and there're a src folder in that branch. )

**Comment by JohnnyMorganz** [comment] 2021-08-30 12:10
Closing this as its not a bug, but an issue with your workflow. If you have any more questions about it, do let me know

**Closed by JohnnyMorganz** 2021-08-30 12:10 UTC
