### ISSUE TITLE
`--respect-ignores`: does not correctly ignore folders without the globbing pattern 

### ISSUE THREAD

**Issue by wookayin** [JohnnyMorganz/StyLua#845] opened 2024-01-03 05:36 UTC
Problem: `.styluaignore` does not ignore **folders** or **directories** like `.gitignore`, `.rgignore`, etc. do. Instead, full globbing patterns (`*.lua` or `**/*.lua`) would be needed to ignore all files under a directory.

EDIT: This seems to be the case only when used with `--respect-ignores <pattern>`.

## Example

(Tested with stylua 0.19.1, which already includes #765)

Let's say we have `src/foo.lua` and `build/foo.lua` in the project root (with `.styluaignore`).

### Current behavior

With the following `.styluaignore`:
```
build/
```

`$ stylua --check --respect-ignores build/foo.lua` would not ignore `build/foo.lua`.

### Expected behavior

`build/foo.lua` should be ignored.

### Current behavior (2)

With the following `.styluaignore`:
```
build/**/*.lua
```

`$ stylua --check --respect-ignores build/foo.lua` does ignore `build/foo.lua`. This behavior is consistent with `.gitignore`, etc.

**Comment by JohnnyMorganz** [comment] 2024-01-03 09:44
This is fixed in the next release. The issue is that you are explicitly passing file names that are ignored. Our default behaviour is that explicit file paths will override ignores.

Next release adds a flag `--respect-ignores` that will work here.

Maybe I forgot to update the README though, I should do this.

See https://github.com/JohnnyMorganz/StyLua/issues/751

**Comment by JohnnyMorganz** [comment] 2024-01-03 09:47
We use the ignore crate to provide gitignore-style ignores: https://docs.rs/ignore/latest/ignore/. This may actually be an issue upstream, but I will verify it myself first

**Comment by wookayin** [comment] 2024-01-03 10:22
Yes, I find that ignoring a (sub)directory works when scanning, i.e., "stylua ." (unit tests: https://github.com/JohnnyMorganz/StyLua/blob/v0.19.1/src/cli/main.rs#L723), but doesn't work only for `--respect-ignores <individual filename>`.

**Closed** 2024-01-20 12:37 UTC
Labels: bug
