### ISSUE TITLE
Unusual formatting when pasting comments

### ISSUE THREAD

**Issue by LastTalon** [JohnnyMorganz/StyLua#68] opened 2021-03-04 02:03 UTC
StyLua seems to format the whole document when pasting comments using the VS Code extension, in this case `-- @from @{Enumerable}`. This only happens with `Format On Paste` enabled. Disabling the setting solves this problem. Furthermore, it seems to be doing some very unusual formatting.

A visual:
![](https://puu.sh/HlYOw/c7ee065412.gif)

Seems distinct, but likely related to #67.

**Comment by JohnnyMorganz** [comment] 2021-03-04 09:05
I think this is a duplicate of #67, it is the same underlying issue

**Comment by JohnnyMorganz** [comment] 2021-03-04 12:08
Nevermind, this is sightly different. I seem to have forgotten to do a "in range" check for the last statements (return/break etc.)

**Closed** 2021-03-04 12:53 UTC
Labels: bug
