### ISSUE TITLE
Stylua doesn't enforce column_width correctly with some inputs

### ISSUE THREAD

**Issue by Olaroll** [JohnnyMorganz/StyLua#850] opened 2024-01-18 16:10 UTC
## Overview
With certain minified inputs, it seems like stylua doesn't enforce column_width correctly.

This causes it to settle in a result that is different from what it would usually produce.

Running stylua again will produce the correctly formatted code.

## Steps to reproduce
1. Create a file `test.lua` with this content: 
```lua
return {StructureRiverShelter3={MaterialRiverWood=1,MaterialRiverMortar=1,MaterialRiverStone=3,},}
```
2. Run Stylua using `stylua --column-width 100 test.lua`
```lua
return { StructureRiverShelter3 = { MaterialRiverWood = 1, MaterialRiverMortar = 1, MaterialRiverStone = 3 } }
```
3. Run Stylua again with the same command:
```lua
return {
	StructureRiverShelter3 = {
		MaterialRiverWood = 1,
		MaterialRiverMortar = 1,
		MaterialRiverStone = 3,
	},
}
```

**Comment by JohnnyMorganz** [comment] 2024-01-19 21:55
This looks like a duplicate of #484. Unfortunately this isn't so easy to solve with the current way stylua is set up

**Comment by Olaroll** [comment] 2024-01-24 09:08
Yes, seems like it's a duplicate. Feel free to close it

**Closed** 2024-01-27 10:23 UTC
Labels: duplicate
