### ISSUE TITLE
Using excessive amounts of memory on very large file

### ISSUE THREAD

**Issue by matthargett** [JohnnyMorganz/StyLua#362] opened 2022-02-06 19:26 UTC
On an i9 Macbook Pro, StyLua has 16 worker threads. When running StyLua on the RegExp community library from the Roblox developer forum, the memory usage of the process continually expands eventually causing a 32GB RAM laptop to start swapping, which dramatically slows down formatting. 
<img width="579" alt="image" src="https://user-images.githubusercontent.com/1550766/152697893-15a399dc-e872-4ae6-b081-13b1a34fdb40.png">

This isn't a huge deal for most use cases, but it does slow down my ability to regression test ahead of new StyLua releases. There's probably some low-hanging fruit here where something isn't getting freed/closed once a file is done processing. This may ultimately be a full-moon issue.

**Comment by JohnnyMorganz** [comment] 2022-02-06 20:15
The cause was narrowed down to an *extremely* large file which is causing this issue, rather than an incremental build up of leaking memory.
Not sure how much we can do about it, but I guess we can try

**Comment by JohnnyMorganz** [comment] 2022-06-25 12:16
Closing this as I don't think there will be any improvements to this in the foreseeable future (the file was autogenerated ~6MB)

**Closed by JohnnyMorganz** 2022-06-25 12:16 UTC
