### ISSUE TITLE
Errors with goto statements

### ISSUE THREAD

**Issue by tobealive** [JohnnyMorganz/StyLua#644] opened 2023-01-31 01:16 UTC
- This won't format:
  
  ````lua
  ---@param col number
  ---@param amt number
  local function tint(col, amt)
  	if type(col) == "number" then goto work end

  	if not is_hex(col) then return end
  	col = tonumber(col, 16) 
  	
  	::work::
  	-- do some work ...
  	local result = "did some work" -- <-- the error is shouting at this?

  	return result
  end
  ````
  Error: `error: could not format file <filename>.lua: error parsing: error occurred while creating ast
: unexpected token 'local'. (starting from line <ln>, character 2 and ending on line <ln>, character 7)
additional information: expected identifier after `::`

- But this will format (Which is the same but instead of using an early return, the condition in line 5 is wrapped in an if else block)
  
  ```lua
  ---@param col number
  ---@param amt number
  local function tint(col, amt)
  	if type(col) == "number" then goto work end

  	if not is_hex(col) then
  		return
  	else
  		col = tonumber(col, 16)
  	end

  	::work::
  	-- do some work ...
  	local result = "did some work"

  	return result
  end
  ```

**Comment by JohnnyMorganz** [comment] 2023-01-31 10:48
See https://github.com/JohnnyMorganz/StyLua/issues/407 which this is a duplicate of.

This happens due to the conflict of Lua 5.2 parsing and Luau parsing, where the latter treats it as a type assertion operator on the previous expression `tonumber(col, 16) :: work`

Right now, you need to manually build the binary for Lua 5.2 specifically - `cargo install stylua --features lua52`

**Comment by JohnnyMorganz** [comment] 2023-02-07 13:35
Closing this out as its a duplicate. Let me know if you require any further help

**Closed by JohnnyMorganz** 2023-02-07 13:35 UTC
