### ISSUE TITLE
Column formatting

### ISSUE THREAD

**Issue by sarmong** [JohnnyMorganz/StyLua#415] opened 2022-03-21 16:39 UTC
Is it possible to format (or at least keep the formatting) in a column structure?

Here's what I mean (the spaces will shrink after formatting)
![image](https://user-images.githubusercontent.com/42828375/159309768-51aba214-7fca-4e8a-bbf5-8cd4be5fcb65.png)

It is something that e.g. [shfmt](https://github.com/mvdan/sh) does.

**Comment by JohnnyMorganz** [comment] 2022-03-21 16:45
Alignment is something I'm somewhat interested in looking at, and it was also suggested in another position in #252, but there are a few reasons why it can be an issue:
1) aligning causes a lot of diff noise (if something forces the alignment to change, then all other comments get changed unnecessarily)
2) it is difficult to calculate alignment nicely (i havent looked into this fully yet). It would probably be a two-pass formatting, where we first format normally then align comments afterwards.

If alignment was to be added, it would most likely be behind an option due to issue (1), as diff noise is not wanted by a lot of people.

**Comment by sarmong** [comment] 2022-03-21 16:52
Behind an option would be great as well!

Also, maybe it is possible to do alignment only if there is 2+ spaces in any of the lines inside one codeblock? And if every line has only one space - don't align.

**Comment by JohnnyMorganz** [comment] 2022-03-25 14:22
Going to fold this in as a duplicate of #252 for now, as it seems to be the same idea of aligning trailing comments

**Closed by JohnnyMorganz** 2022-03-25 14:22 UTC
